<?php
/**
 * TeaSpace Panel – Web Installer (PHP 8+)
 */

declare(strict_types=1);

session_start();

const INSTALL_LOCK = __DIR__ . '/install.lock';
const ROOT_DIR = __DIR__ . '/..';
const CONFIG_FILE = ROOT_DIR . '/app/controller/config.php';
const HTACCESS_FILE = ROOT_DIR . '/.htaccess';
const SQL_FILE = ROOT_DIR . '/teaspace.sql';

$installed = is_file(INSTALL_LOCK);

/**
 * Detect public base URL and rewrite base path.
 */
function install_detect_base(): array
{
    $https = (!empty($_SERVER['HTTPS']) && $_SERVER['HTTPS'] !== 'off')
        || (isset($_SERVER['SERVER_PORT']) && (int) $_SERVER['SERVER_PORT'] === 443)
        || (isset($_SERVER['HTTP_X_FORWARDED_PROTO']) && $_SERVER['HTTP_X_FORWARDED_PROTO'] === 'https');

    $scheme = $https ? 'https' : 'http';
    $host = $_SERVER['HTTP_HOST'] ?? 'localhost';
    $script = str_replace('\\', '/', dirname($_SERVER['SCRIPT_NAME'] ?? ''));
    // /path/install → /path/
    $basePath = rtrim(dirname($script), '/\\');
    if ($basePath === '' || $basePath === '.') {
        $basePath = '';
    }
    $url = $scheme . '://' . $host . ($basePath === '' ? '/' : $basePath . '/');
    $rewriteBase = $basePath === '' ? '/' : $basePath . '/';

    return ['url' => $url, 'rewrite_base' => $rewriteBase];
}

function install_requirements(): array
{
    $checks = [];
    $checks[] = [
        'label' => 'PHP 8.1 oder neuer',
        'ok' => version_compare(PHP_VERSION, '8.1.0', '>='),
        'info' => 'Aktuell: ' . PHP_VERSION,
    ];

    foreach (['pdo', 'pdo_mysql', 'curl', 'mbstring', 'json', 'openssl'] as $ext) {
        $checks[] = [
            'label' => 'Extension: ' . $ext,
            'ok' => extension_loaded($ext),
            'info' => extension_loaded($ext) ? 'geladen' : 'fehlt',
        ];
    }

    $checks[] = [
        'label' => 'config.php beschreibbar',
        'ok' => is_writable(dirname(CONFIG_FILE)) || (is_file(CONFIG_FILE) && is_writable(CONFIG_FILE)),
        'info' => dirname(CONFIG_FILE),
    ];
    $checks[] = [
        'label' => '.htaccess beschreibbar',
        'ok' => is_writable(HTACCESS_FILE) || is_writable(ROOT_DIR),
        'info' => HTACCESS_FILE,
    ];
    $checks[] = [
        'label' => 'SQL-Dump vorhanden',
        'ok' => is_file(SQL_FILE),
        'info' => 'teaspace.sql',
    ];
    $checks[] = [
        'label' => 'Composer Vendor',
        'ok' => is_file(ROOT_DIR . '/vendor/autoload.php'),
        'info' => is_file(ROOT_DIR . '/vendor/autoload.php') ? 'vorhanden' : 'composer install ausführen',
    ];

    return $checks;
}

function install_escape(string $value): string
{
    return str_replace(["\\", "'"], ["\\\\", "\\'"], $value);
}

function install_write_config(array $d): void
{
    $sandbox = !empty($d['paypal_sandbox']) ? 'true' : 'false';
    $content = <<<PHP
<?php

/**
 * Application configuration.
 * Generated by the web installer on {$d['generated_at']}.
 */

\$db_host = '{$d['db_host']}';
\$db_name = '{$d['db_name']}';
\$db_username = '{$d['db_username']}';
\$db_password = '{$d['db_password']}';

\$siteName = '{$d['site_name']}';

\$grecaptchaSiteKey = '{$d['grecaptcha_site']}';
\$grecaptchaSecret = '{$d['grecaptcha_secret']}';

\$url = '{$d['url']}';
\$cdnUrl = \$url . 'assets/style/';
\$picUrl = \$url . 'assets/images/';

\$mail_host = '{$d['mail_host']}';
\$mail_port = {$d['mail_port']};
\$mail_encryption = '{$d['mail_encryption']}';
\$mail_username = '{$d['mail_username']}';
\$mail_password = '{$d['mail_password']}';
\$mail_from = '{$d['mail_from']}';
\$mail_from_name = '{$d['mail_from_name']}';

\$mollie_api_key = '{$d['mollie_api_key']}';

\$paypal_email = '{$d['paypal_email']}';
\$paypal_sandbox = {$sandbox};

\$telegram_token = '{$d['telegram_token']}';
\$telegram_chat_id = '{$d['telegram_chat_id']}';

\$cron_key = '{$d['cron_key']}';

PHP;

    if (file_put_contents(CONFIG_FILE, $content) === false) {
        throw new RuntimeException('config.php konnte nicht geschrieben werden.');
    }
}

function install_update_htaccess(string $rewriteBase): void
{
    if (!is_file(HTACCESS_FILE)) {
        return;
    }
    $ht = file_get_contents(HTACCESS_FILE);
    if ($ht === false) {
        return;
    }
    if (preg_match('/RewriteBase\s+.+/i', $ht)) {
        $ht = preg_replace('/RewriteBase\s+.+/i', 'RewriteBase ' . $rewriteBase, $ht, 1);
    } else {
        $ht = preg_replace('/RewriteEngine\s+on/i', "RewriteEngine on\n    RewriteBase " . $rewriteBase, $ht, 1);
    }
    file_put_contents(HTACCESS_FILE, $ht);
}

function install_import_sql(PDO $pdo): void
{
    $sql = file_get_contents(SQL_FILE);
    if ($sql === false) {
        throw new RuntimeException('teaspace.sql konnte nicht gelesen werden.');
    }

    // Strip comments / phpMyAdmin meta
    $sql = preg_replace('/^--.*$/m', '', $sql);
    $sql = preg_replace('/\/\*![0-9]{5}.*?\*\//s', '', $sql);

    $pdo->exec('SET FOREIGN_KEY_CHECKS=0');
    $buffer = '';
    foreach (explode(";\n", str_replace("\r\n", "\n", $sql)) as $chunk) {
        $chunk = trim($chunk);
        if ($chunk === '') {
            continue;
        }
        $buffer = $chunk;
        try {
            $pdo->exec($buffer);
        } catch (PDOException $e) {
            // Ignore empty / duplicate noise where possible
            if (stripos($e->getMessage(), 'already exists') === false) {
                throw new RuntimeException('SQL-Fehler: ' . $e->getMessage() . ' — Statement: ' . substr($buffer, 0, 120));
            }
        }
    }
    $pdo->exec('SET FOREIGN_KEY_CHECKS=1');
}

function install_create_admin(PDO $pdo, string $username, string $email, string $password): void
{
    $hash = password_hash($password, PASSWORD_BCRYPT, ['cost' => 10]);
    $stmt = $pdo->prepare(
        "INSERT INTO `users` (`username`, `firstname`, `lastname`, `email`, `password`, `state`, `role`, `amount`)
         VALUES (?, ?, ?, ?, ?, 'active', 'admin', 0.00)"
    );
    $stmt->execute([$username, 'Admin', 'Admin', $email, $hash]);
}

$base = install_detect_base();
$step = isset($_GET['step']) ? (int) $_GET['step'] : 1;
if ($installed) {
    $step = 99;
}

$errors = [];
$success = null;
$requirements = install_requirements();
$allRequirementsOk = !in_array(false, array_column($requirements, 'ok'), true);

if ($_SERVER['REQUEST_METHOD'] === 'POST' && !$installed) {
    $action = $_POST['action'] ?? '';

    if ($action === 'test_db') {
        try {
            $dsn = 'mysql:host=' . trim($_POST['db_host'] ?? '') . ';charset=utf8mb4';
            $pdo = new PDO($dsn, trim($_POST['db_username'] ?? ''), (string) ($_POST['db_password'] ?? ''), [
                PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
            ]);
            $dbName = trim($_POST['db_name'] ?? '');
            if ($dbName === '') {
                throw new RuntimeException('Datenbankname fehlt.');
            }
            $pdo->exec('CREATE DATABASE IF NOT EXISTS `' . str_replace('`', '``', $dbName) . '` CHARACTER SET utf8mb4 COLLATE utf8mb4_unicode_ci');
            $pdo->exec('USE `' . str_replace('`', '``', $dbName) . '`');
            $_SESSION['install'] = array_merge($_SESSION['install'] ?? [], [
                'db_host' => trim($_POST['db_host']),
                'db_name' => $dbName,
                'db_username' => trim($_POST['db_username']),
                'db_password' => (string) ($_POST['db_password'] ?? ''),
            ]);
            $success = 'Datenbankverbindung erfolgreich. Datenbank wurde ggf. angelegt.';
            $step = 3;
        } catch (Throwable $e) {
            $errors[] = $e->getMessage();
            $step = 2;
        }
    }

    if ($action === 'save_settings') {
        $url = rtrim(trim($_POST['url'] ?? ''), '/') . '/';
        $rewriteBase = trim($_POST['rewrite_base'] ?? '/');
        if ($rewriteBase === '') {
            $rewriteBase = '/';
        }
        if ($rewriteBase[0] !== '/') {
            $rewriteBase = '/' . $rewriteBase;
        }
        if (substr($rewriteBase, -1) !== '/') {
            $rewriteBase .= '/';
        }

        $_SESSION['install'] = array_merge($_SESSION['install'] ?? [], [
            'site_name' => trim($_POST['site_name'] ?? 'Tea-Space'),
            'url' => $url,
            'rewrite_base' => $rewriteBase,
            'grecaptcha_site' => trim($_POST['grecaptcha_site'] ?? ''),
            'grecaptcha_secret' => trim($_POST['grecaptcha_secret'] ?? ''),
            'mail_host' => trim($_POST['mail_host'] ?? ''),
            'mail_port' => (int) ($_POST['mail_port'] ?? 465),
            'mail_encryption' => trim($_POST['mail_encryption'] ?? 'ssl'),
            'mail_username' => trim($_POST['mail_username'] ?? ''),
            'mail_password' => (string) ($_POST['mail_password'] ?? ''),
            'mail_from' => trim($_POST['mail_from'] ?? ''),
            'mail_from_name' => trim($_POST['mail_from_name'] ?? 'Kundendienst'),
            'mollie_api_key' => trim($_POST['mollie_api_key'] ?? ''),
            'paypal_email' => trim($_POST['paypal_email'] ?? ''),
            'paypal_sandbox' => isset($_POST['paypal_sandbox']),
            'telegram_token' => trim($_POST['telegram_token'] ?? ''),
            'telegram_chat_id' => trim($_POST['telegram_chat_id'] ?? ''),
            'cron_key' => trim($_POST['cron_key'] ?? '') ?: bin2hex(random_bytes(16)),
        ]);
        $step = 4;
    }

    if ($action === 'finish') {
        $data = $_SESSION['install'] ?? [];
        $adminUser = trim($_POST['admin_username'] ?? '');
        $adminEmail = trim($_POST['admin_email'] ?? '');
        $adminPass = (string) ($_POST['admin_password'] ?? '');
        $adminPass2 = (string) ($_POST['admin_password2'] ?? '');

        if ($adminUser === '' || $adminEmail === '' || $adminPass === '') {
            $errors[] = 'Bitte alle Admin-Felder ausfüllen.';
            $step = 4;
        } elseif (!filter_var($adminEmail, FILTER_VALIDATE_EMAIL)) {
            $errors[] = 'Ungültige Admin-E-Mail.';
            $step = 4;
        } elseif (strlen($adminPass) < 8) {
            $errors[] = 'Passwort muss mindestens 8 Zeichen haben.';
            $step = 4;
        } elseif ($adminPass !== $adminPass2) {
            $errors[] = 'Passwörter stimmen nicht überein.';
            $step = 4;
        } elseif (empty($data['db_host']) || empty($data['db_name'])) {
            $errors[] = 'Datenbankdaten fehlen – bitte Schritt 2 wiederholen.';
            $step = 2;
        } else {
            try {
                $dsn = 'mysql:host=' . $data['db_host'] . ';dbname=' . $data['db_name'] . ';charset=utf8mb4';
                $pdo = new PDO($dsn, $data['db_username'], $data['db_password'], [
                    PDO::ATTR_ERRMODE => PDO::ERRMODE_EXCEPTION,
                ]);

                install_import_sql($pdo);
                install_create_admin($pdo, $adminUser, $adminEmail, $adminPass);

                $cfg = [
                    'generated_at' => date('Y-m-d H:i:s'),
                    'db_host' => install_escape($data['db_host']),
                    'db_name' => install_escape($data['db_name']),
                    'db_username' => install_escape($data['db_username']),
                    'db_password' => install_escape($data['db_password']),
                    'site_name' => install_escape($data['site_name'] ?? 'Tea-Space'),
                    'url' => install_escape($data['url'] ?? $base['url']),
                    'grecaptcha_site' => install_escape($data['grecaptcha_site'] ?? ''),
                    'grecaptcha_secret' => install_escape($data['grecaptcha_secret'] ?? ''),
                    'mail_host' => install_escape($data['mail_host'] ?? ''),
                    'mail_port' => (int) ($data['mail_port'] ?? 465),
                    'mail_encryption' => install_escape($data['mail_encryption'] ?? 'ssl'),
                    'mail_username' => install_escape($data['mail_username'] ?? ''),
                    'mail_password' => install_escape($data['mail_password'] ?? ''),
                    'mail_from' => install_escape($data['mail_from'] ?? ''),
                    'mail_from_name' => install_escape($data['mail_from_name'] ?? 'Kundendienst'),
                    'mollie_api_key' => install_escape($data['mollie_api_key'] ?? ''),
                    'paypal_email' => install_escape($data['paypal_email'] ?? ''),
                    'paypal_sandbox' => !empty($data['paypal_sandbox']),
                    'telegram_token' => install_escape($data['telegram_token'] ?? ''),
                    'telegram_chat_id' => install_escape($data['telegram_chat_id'] ?? ''),
                    'cron_key' => install_escape($data['cron_key'] ?? bin2hex(random_bytes(16))),
                ];

                install_write_config($cfg);
                install_update_htaccess($data['rewrite_base'] ?? $base['rewrite_base']);

                file_put_contents(INSTALL_LOCK, 'installed:' . date('c') . PHP_EOL);
                unset($_SESSION['install']);
                $installed = true;
                $step = 99;
                $success = 'Installation abgeschlossen.';
            } catch (Throwable $e) {
                $errors[] = $e->getMessage();
                $step = 4;
            }
        }
    }
}

$s = $_SESSION['install'] ?? [];
?>
<!DOCTYPE html>
<html lang="de">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>TeaSpace Installer</title>
    <link rel="preconnect" href="https://fonts.googleapis.com">
    <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin>
    <link href="https://fonts.googleapis.com/css2?family=Outfit:wght@400;500;600;700&family=IBM+Plex+Sans:wght@400;500;600&display=swap" rel="stylesheet">
    <style>
        :root {
            --bg0: #0b1220;
            --bg1: #121c2e;
            --panel: rgba(18, 28, 46, 0.88);
            --line: rgba(148, 163, 184, 0.18);
            --text: #e8eef7;
            --muted: #94a3b8;
            --accent: #14b8a6;
            --accent-2: #0d9488;
            --warn: #f59e0b;
            --danger: #ef4444;
            --ok: #22c55e;
            --radius: 14px;
            --shadow: 0 24px 60px rgba(0, 0, 0, 0.35);
        }
        * { box-sizing: border-box; }
        html, body { margin: 0; min-height: 100%; }
        body {
            font-family: "IBM Plex Sans", system-ui, sans-serif;
            color: var(--text);
            background:
                radial-gradient(1200px 600px at 10% -10%, rgba(20, 184, 166, 0.18), transparent 55%),
                radial-gradient(900px 500px at 100% 0%, rgba(56, 189, 248, 0.12), transparent 50%),
                linear-gradient(160deg, var(--bg0), var(--bg1));
            background-attachment: fixed;
        }
        .wrap {
            width: min(920px, calc(100% - 2rem));
            margin: 0 auto;
            padding: 3rem 0 4rem;
        }
        .brand {
            display: flex;
            align-items: baseline;
            gap: 0.75rem;
            margin-bottom: 1.5rem;
            animation: rise 0.5s ease both;
        }
        .brand h1 {
            font-family: Outfit, sans-serif;
            font-size: clamp(1.8rem, 4vw, 2.4rem);
            margin: 0;
            letter-spacing: -0.03em;
        }
        .brand span {
            color: var(--muted);
            font-size: 0.95rem;
        }
        .panel {
            background: var(--panel);
            border: 1px solid var(--line);
            border-radius: var(--radius);
            box-shadow: var(--shadow);
            backdrop-filter: blur(10px);
            overflow: hidden;
            animation: rise 0.55s ease 0.05s both;
        }
        .steps {
            display: grid;
            grid-template-columns: repeat(4, 1fr);
            border-bottom: 1px solid var(--line);
        }
        .steps div {
            padding: 0.9rem 0.6rem;
            text-align: center;
            font-size: 0.82rem;
            color: var(--muted);
            position: relative;
        }
        .steps div.active { color: var(--text); font-weight: 600; }
        .steps div.done { color: var(--accent); }
        .steps div::after {
            content: "";
            position: absolute;
            left: 15%;
            right: 15%;
            bottom: 0;
            height: 2px;
            background: transparent;
            transition: background 0.25s ease;
        }
        .steps div.active::after,
        .steps div.done::after { background: var(--accent); }
        .body { padding: 1.75rem 1.5rem 1.5rem; }
        h2 {
            font-family: Outfit, sans-serif;
            margin: 0 0 0.4rem;
            font-size: 1.35rem;
            letter-spacing: -0.02em;
        }
        .lead { color: var(--muted); margin: 0 0 1.4rem; line-height: 1.55; }
        .grid {
            display: grid;
            grid-template-columns: 1fr 1fr;
            gap: 1rem;
        }
        .grid .full { grid-column: 1 / -1; }
        label {
            display: block;
            font-size: 0.85rem;
            color: var(--muted);
            margin-bottom: 0.35rem;
        }
        input, select {
            width: 100%;
            border: 1px solid var(--line);
            background: rgba(2, 8, 20, 0.45);
            color: var(--text);
            border-radius: 10px;
            padding: 0.75rem 0.85rem;
            font: inherit;
            outline: none;
            transition: border-color 0.2s ease, box-shadow 0.2s ease;
        }
        input:focus, select:focus {
            border-color: rgba(20, 184, 166, 0.7);
            box-shadow: 0 0 0 3px rgba(20, 184, 166, 0.18);
        }
        .check {
            display: flex;
            align-items: center;
            gap: 0.55rem;
            margin-top: 0.4rem;
            color: var(--muted);
        }
        .check input { width: auto; }
        .req {
            list-style: none;
            margin: 0;
            padding: 0;
            display: grid;
            gap: 0.55rem;
        }
        .req li {
            display: flex;
            justify-content: space-between;
            gap: 1rem;
            padding: 0.8rem 0.95rem;
            border: 1px solid var(--line);
            border-radius: 10px;
            background: rgba(2, 8, 20, 0.28);
        }
        .badge {
            font-size: 0.78rem;
            font-weight: 600;
            padding: 0.2rem 0.55rem;
            border-radius: 999px;
            white-space: nowrap;
        }
        .badge.ok { background: rgba(34, 197, 94, 0.15); color: var(--ok); }
        .badge.bad { background: rgba(239, 68, 68, 0.15); color: #fca5a5; }
        .alert {
            padding: 0.85rem 1rem;
            border-radius: 10px;
            margin-bottom: 1rem;
            line-height: 1.45;
        }
        .alert.error { background: rgba(239, 68, 68, 0.12); border: 1px solid rgba(239, 68, 68, 0.35); color: #fecaca; }
        .alert.ok { background: rgba(34, 197, 94, 0.12); border: 1px solid rgba(34, 197, 94, 0.35); color: #bbf7d0; }
        .actions {
            display: flex;
            justify-content: space-between;
            gap: 0.75rem;
            margin-top: 1.5rem;
            flex-wrap: wrap;
        }
        .btn {
            appearance: none;
            border: 0;
            border-radius: 999px;
            padding: 0.8rem 1.25rem;
            font: inherit;
            font-weight: 600;
            cursor: pointer;
            text-decoration: none;
            display: inline-flex;
            align-items: center;
            justify-content: center;
            min-height: 44px;
            transition: transform 0.15s ease, background 0.2s ease, opacity 0.2s ease;
        }
        .btn:hover { transform: translateY(-1px); }
        .btn:active { transform: translateY(0); }
        .btn-primary { background: linear-gradient(135deg, var(--accent), var(--accent-2)); color: #042f2e; }
        .btn-ghost { background: transparent; color: var(--muted); border: 1px solid var(--line); }
        .btn:disabled { opacity: 0.45; cursor: not-allowed; transform: none; }
        .done-box { text-align: center; padding: 1rem 0 0.5rem; }
        .done-box p { color: var(--muted); line-height: 1.6; }
        code {
            font-family: ui-monospace, SFMono-Regular, Menlo, Consolas, monospace;
            font-size: 0.86em;
            background: rgba(2, 8, 20, 0.5);
            padding: 0.12rem 0.35rem;
            border-radius: 6px;
        }
        @media (max-width: 720px) {
            .grid { grid-template-columns: 1fr; }
            .steps { grid-template-columns: 1fr 1fr; }
        }
        @keyframes rise {
            from { opacity: 0; transform: translateY(10px); }
            to { opacity: 1; transform: translateY(0); }
        }
        @media (prefers-reduced-motion: reduce) {
            * { animation: none !important; transition: none !important; }
        }
    </style>
</head>
<body>
<div class="wrap">
    <div class="brand">
        <h1>TeaSpace</h1>
        <span>Panel Installer · PHP <?= htmlspecialchars(PHP_VERSION) ?></span>
    </div>

    <div class="panel">
        <?php if ($step !== 99): ?>
        <div class="steps">
            <div class="<?= $step === 1 ? 'active' : ($step > 1 ? 'done' : '') ?>">1 · System</div>
            <div class="<?= $step === 2 ? 'active' : ($step > 2 ? 'done' : '') ?>">2 · Datenbank</div>
            <div class="<?= $step === 3 ? 'active' : ($step > 3 ? 'done' : '') ?>">3 · Einstellungen</div>
            <div class="<?= $step === 4 ? 'active' : ($step > 4 ? 'done' : '') ?>">4 · Admin</div>
        </div>
        <?php endif; ?>

        <div class="body">
            <?php foreach ($errors as $err): ?>
                <div class="alert error"><?= htmlspecialchars($err) ?></div>
            <?php endforeach; ?>
            <?php if ($success): ?>
                <div class="alert ok"><?= htmlspecialchars($success) ?></div>
            <?php endif; ?>

            <?php if ($step === 1): ?>
                <h2>Systemprüfung</h2>
                <p class="lead">Bevor die Installation startet, prüfen wir PHP-Version, Extensions und Schreibrechte.</p>
                <ul class="req">
                    <?php foreach ($requirements as $check): ?>
                        <li>
                            <div>
                                <strong><?= htmlspecialchars($check['label']) ?></strong><br>
                                <span style="color:var(--muted);font-size:0.85rem"><?= htmlspecialchars($check['info']) ?></span>
                            </div>
                            <span class="badge <?= $check['ok'] ? 'ok' : 'bad' ?>"><?= $check['ok'] ? 'OK' : 'Fehler' ?></span>
                        </li>
                    <?php endforeach; ?>
                </ul>
                <div class="actions">
                    <span></span>
                    <?php if ($allRequirementsOk): ?>
                        <a class="btn btn-primary" href="?step=2">Weiter zur Datenbank</a>
                    <?php else: ?>
                        <button class="btn btn-primary" disabled>Bitte Anforderungen erfüllen</button>
                    <?php endif; ?>
                </div>

            <?php elseif ($step === 2): ?>
                <h2>Datenbank</h2>
                <p class="lead">Verbindung zur MySQL/MariaDB-Datenbank. Die Datenbank wird automatisch angelegt, falls sie fehlt.</p>
                <form method="post">
                    <input type="hidden" name="action" value="test_db">
                    <div class="grid">
                        <div>
                            <label for="db_host">Host</label>
                            <input id="db_host" name="db_host" required value="<?= htmlspecialchars($s['db_host'] ?? 'localhost') ?>">
                        </div>
                        <div>
                            <label for="db_name">Datenbankname</label>
                            <input id="db_name" name="db_name" required value="<?= htmlspecialchars($s['db_name'] ?? 'teaspace') ?>">
                        </div>
                        <div>
                            <label for="db_username">Benutzer</label>
                            <input id="db_username" name="db_username" required value="<?= htmlspecialchars($s['db_username'] ?? 'root') ?>">
                        </div>
                        <div>
                            <label for="db_password">Passwort</label>
                            <input id="db_password" name="db_password" type="password" value="<?= htmlspecialchars($s['db_password'] ?? '') ?>">
                        </div>
                    </div>
                    <div class="actions">
                        <a class="btn btn-ghost" href="?step=1">Zurück</a>
                        <button class="btn btn-primary" type="submit">Verbindung testen &amp; weiter</button>
                    </div>
                </form>

            <?php elseif ($step === 3): ?>
                <h2>Einstellungen</h2>
                <p class="lead">Site-URL, SMTP und optionale Zahlungs-/Telegram-Integrationen. Felder können später in <code>config.php</code> angepasst werden.</p>
                <form method="post">
                    <input type="hidden" name="action" value="save_settings">
                    <div class="grid">
                        <div>
                            <label for="site_name">Seitenname</label>
                            <input id="site_name" name="site_name" required value="<?= htmlspecialchars($s['site_name'] ?? 'Tea-Space') ?>">
                        </div>
                        <div>
                            <label for="rewrite_base">RewriteBase (.htaccess)</label>
                            <input id="rewrite_base" name="rewrite_base" required value="<?= htmlspecialchars($s['rewrite_base'] ?? $base['rewrite_base']) ?>">
                        </div>
                        <div class="full">
                            <label for="url">Öffentliche URL (mit Slash am Ende)</label>
                            <input id="url" name="url" required value="<?= htmlspecialchars($s['url'] ?? $base['url']) ?>">
                        </div>

                        <div class="full"><h2 style="font-size:1.05rem;margin:0.6rem 0 0">E-Mail (SMTP)</h2></div>
                        <div>
                            <label for="mail_host">SMTP Host</label>
                            <input id="mail_host" name="mail_host" value="<?= htmlspecialchars($s['mail_host'] ?? '') ?>">
                        </div>
                        <div>
                            <label for="mail_port">Port</label>
                            <input id="mail_port" name="mail_port" type="number" value="<?= htmlspecialchars((string) ($s['mail_port'] ?? 465)) ?>">
                        </div>
                        <div>
                            <label for="mail_encryption">Verschlüsselung</label>
                            <select id="mail_encryption" name="mail_encryption">
                                <?php foreach (['ssl', 'tls', ''] as $enc): ?>
                                    <option value="<?= htmlspecialchars($enc) ?>" <?= ($s['mail_encryption'] ?? 'ssl') === $enc ? 'selected' : '' ?>><?= $enc === '' ? 'keine' : strtoupper($enc) ?></option>
                                <?php endforeach; ?>
                            </select>
                        </div>
                        <div>
                            <label for="mail_from_name">Absendername</label>
                            <input id="mail_from_name" name="mail_from_name" value="<?= htmlspecialchars($s['mail_from_name'] ?? 'Kundendienst') ?>">
                        </div>
                        <div>
                            <label for="mail_username">SMTP Benutzer</label>
                            <input id="mail_username" name="mail_username" value="<?= htmlspecialchars($s['mail_username'] ?? '') ?>">
                        </div>
                        <div>
                            <label for="mail_password">SMTP Passwort</label>
                            <input id="mail_password" name="mail_password" type="password" value="<?= htmlspecialchars($s['mail_password'] ?? '') ?>">
                        </div>
                        <div class="full">
                            <label for="mail_from">Absender-E-Mail</label>
                            <input id="mail_from" name="mail_from" value="<?= htmlspecialchars($s['mail_from'] ?? '') ?>">
                        </div>

                        <div class="full"><h2 style="font-size:1.05rem;margin:0.6rem 0 0">Optional</h2></div>
                        <div>
                            <label for="mollie_api_key">Mollie API Key</label>
                            <input id="mollie_api_key" name="mollie_api_key" value="<?= htmlspecialchars($s['mollie_api_key'] ?? '') ?>">
                        </div>
                        <div>
                            <label for="paypal_email">PayPal E-Mail</label>
                            <input id="paypal_email" name="paypal_email" value="<?= htmlspecialchars($s['paypal_email'] ?? '') ?>">
                        </div>
                        <div class="full">
                            <label class="check"><input type="checkbox" name="paypal_sandbox" value="1" <?= !empty($s['paypal_sandbox']) ? 'checked' : '' ?>> PayPal Sandbox aktiv</label>
                        </div>
                        <div>
                            <label for="grecaptcha_site">reCAPTCHA Site Key</label>
                            <input id="grecaptcha_site" name="grecaptcha_site" value="<?= htmlspecialchars($s['grecaptcha_site'] ?? '') ?>">
                        </div>
                        <div>
                            <label for="grecaptcha_secret">reCAPTCHA Secret</label>
                            <input id="grecaptcha_secret" name="grecaptcha_secret" value="<?= htmlspecialchars($s['grecaptcha_secret'] ?? '') ?>">
                        </div>
                        <div>
                            <label for="telegram_token">Telegram Bot Token</label>
                            <input id="telegram_token" name="telegram_token" value="<?= htmlspecialchars($s['telegram_token'] ?? '') ?>">
                        </div>
                        <div>
                            <label for="telegram_chat_id">Telegram Chat ID</label>
                            <input id="telegram_chat_id" name="telegram_chat_id" value="<?= htmlspecialchars($s['telegram_chat_id'] ?? '') ?>">
                        </div>
                        <div class="full">
                            <label for="cron_key">Cron-Secret (für <code>crone_job.php?key=…</code>)</label>
                            <input id="cron_key" name="cron_key" value="<?= htmlspecialchars($s['cron_key'] ?? bin2hex(random_bytes(12))) ?>">
                        </div>
                    </div>
                    <div class="actions">
                        <a class="btn btn-ghost" href="?step=2">Zurück</a>
                        <button class="btn btn-primary" type="submit">Weiter zum Admin</button>
                    </div>
                </form>

            <?php elseif ($step === 4): ?>
                <h2>Admin-Konto</h2>
                <p class="lead">Zum Abschluss wird die Datenbank importiert, die Config geschrieben und dein Admin-Benutzer angelegt.</p>
                <form method="post">
                    <input type="hidden" name="action" value="finish">
                    <div class="grid">
                        <div>
                            <label for="admin_username">Benutzername</label>
                            <input id="admin_username" name="admin_username" required value="admin">
                        </div>
                        <div>
                            <label for="admin_email">E-Mail</label>
                            <input id="admin_email" name="admin_email" type="email" required placeholder="admin@example.com">
                        </div>
                        <div>
                            <label for="admin_password">Passwort</label>
                            <input id="admin_password" name="admin_password" type="password" required minlength="8">
                        </div>
                        <div>
                            <label for="admin_password2">Passwort wiederholen</label>
                            <input id="admin_password2" name="admin_password2" type="password" required minlength="8">
                        </div>
                    </div>
                    <div class="actions">
                        <a class="btn btn-ghost" href="?step=3">Zurück</a>
                        <button class="btn btn-primary" type="submit">Installation starten</button>
                    </div>
                </form>

            <?php else: ?>
                <div class="done-box">
                    <h2>Fertig installiert</h2>
                    <p>
                        Das Panel ist bereit. Der Installer ist mit <code>install/install.lock</code> gesperrt.<br>
                        Aus Sicherheitsgründen den Ordner <code>install/</code> nach dem Setup löschen oder den Webzugriff sperren.
                    </p>
                    <div class="actions" style="justify-content:center">
                        <a class="btn btn-primary" href="<?= htmlspecialchars(rtrim(($s['url'] ?? $base['url']), '/') . '/login') ?>">Zum Login</a>
                        <a class="btn btn-ghost" href="<?= htmlspecialchars($base['url']) ?>">Zur Startseite</a>
                    </div>
                </div>
            <?php endif; ?>
        </div>
    </div>
</div>
</body>
</html>
